---

repos:
  - repo: local
    hooks:
    - id: shell-lint
      name: Shell Syntax Check
      description: Check Shell Syntax on ALL staged files with user friendly messages and colors
      entry: ../shell/my_warp.sh -s
      language: script
      files: \.(sh)$
      types: [shell]
